RentalService/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RentalService.Helpers;
using RentalService.Interfaces;
using RentalService.Models;
using System.Security.Claims;

namespace RentalService.Controllers
{
    public class CalendarController : Controller
    {
        private readonly IRentalService _ICalendarService;
        private readonly UserManager<User> _UserManager;


        public CalendarController(IRentalService calendarinterface, UserManager<User> userManager)
        {
            _ICalendarService = calendarinterface;
            _UserManager = userManager;


        }

        [Authorize]
        public IActionResult ViewCalendar()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["Resources"] = JSONListHelper.GetResourcesListJSONString(_ICalendarService.GetEquipments());
            ViewData["Events"] = JSONListHelper.GetEventListJSONString(_ICalendarService.GetRentals(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            return View();
        }


    }
}

RentalService/Controllers/RentalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using RentalService.Interfaces;
using RentalService.Models;
using RentalService.Models.ViewModels;
using System.Security.Claims;

namespace RentalService.Controllers
{
    [Authorize]
    public class RentalController : Controller
    {
        private readonly IRentalService _IRentalService;
        private readonly UserManager<User> _usermanager;


        public RentalController(IRentalService iRentalService, UserManager<User> usermanager)
        {
            _IRentalService = iRentalService;
            _usermanager = usermanager;
        }
        public IActionResult ViewRentals()
        {
            if (TempData["Alert"] != null)
            {
                ViewData["Alert"] = TempData["Alert"];
            }
            return View(_IRentalService.GetRentals(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }

        public IActionResult ViewRental(int id)
        {
            var @rental = _IRentalService.GetRental(id);
            if (@rental == null) { return NotFound(); }
            return View(@rental);
        }



        [HttpGet]
        public IActionResult CreateRental()
        {
            return View(new RentalViewModel(_IRentalService.GetEquipments(), User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }

        [HttpPost]

        public async Task<IActionResult> CreateRental(RentalViewModel vm, IFormCollection form)
        {

            try
            {
                _IRentalService.CreateRental(form);
                TempData["Alert"] = "Success! You have created new rental" + form["EquipmentName"];

                return RedirectToAction("ViewRentals");
            }
            catch (Exception ex)
            {
                ViewData["Alert"] = "An error occurred: " + ex.Message;
                return View(vm);
            }

        }


        [HttpGet]

        public IActionResult UpdateRental(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @rental = _IRentalService.GetRental((int)id);

            if (@rental == null)
            {
                return NotFound();
            }
            var vm = new RentalViewModel(@rental, _IRentalService.GetEquipments(), User.FindFirstValue(ClaimTypes.NameIdentifier));

            return View(vm);
        }
        [HttpPost]

        public async Task<IActionResult> UpdateRental(int id, IFormCollection form)
        {
            try
            {
                _IRentalService.UpdateRental(form);
                TempData["Alert"] = "Success! You modified an rental for: " + form["Rental.RentedEquipmentName"];
                return RedirectToAction(nameof(ViewRentals));
            }
            catch (Exception ex)
            {
                ViewData["Alert"] = "An error occurred: " + ex.Message;
                var vm = new RentalViewModel(_IRentalService.GetRental(id), _IRentalService.GetEquipments(), User.FindFirstValue(ClaimTypes.NameIdentifier));
                return View(vm);
            }
        }

        [HttpGet]

        public IActionResult DeleteRental(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @rental = _IRentalService.GetRental(id);


            if (@rental == null)
            {
                return NotFound();
            }
            return View(@rental);
        }

        [HttpPost, ActionName("DeleteRental")]
        public IActionResult DeleteRentalConfirmed(int id)
        {
            _IRentalService.DeleteRental(id);
            TempData["Alert"] = "You have deleted rental succesfully";

            return RedirectToAction("ViewRentals");
        }
    }
}

RentalService/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RentalService.Interfaces;
using RentalService.Models;
using RentalService.Models.ViewModels;
using System.Security.Claims;

namespace RentalService.Controllers
{
    [Authorize]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _IWarehouseService;
        private readonly UserManager<User> _usermanager;


        public WarehouseController(IWarehouseService iWarehouseService, UserManager<User> usermanager)
        {
            _IWarehouseService = iWarehouseService;
            _usermanager = usermanager;
        }
        public IActionResult List()
        {
            if (TempData["Alert"] != null)
            {
                ViewData["Alert"] = TempData["Alert"];
            }
            return View(_IWarehouseService.GetEquipments(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }



        [HttpGet]
        public IActionResult CreateEquipment()
        {
            return View(new EquipmentViewModel(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }

        [HttpPost]

        public async Task<IActionResult> CreateEquipment(EquipmentViewModel vm, IFormCollection form)
        {

            try
            {
                _IWarehouseService.CreateEquipment(form);
                TempData["Alert"] = "Success! You have created new equipment" + form["EquipmentName"];

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ViewData["Alert"] = "An error occurred: " + ex.Message;

                return View(vm);
            }

        }


        [HttpGet]


        public IActionResult UpdateEquipment(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var updatedEquipment = _IWarehouseService.GetEquipment((int)id);

            if (updatedEquipment == null)
            {
                return NotFound();
            }
            var vm = new EquipmentViewModel(updatedEquipment, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return View(vm);
        }
        [HttpPost]

        public async Task<IActionResult> UpdateEquipment(int id, IFormCollection form)
        {
            try
            {
                _IWarehouseService.UpdateEquipment(form);
                TempData["Alert"] = "Success! You modified an rental for: " + form["Rental.RentedEquipmentName"];
                return RedirectToAction(nameof(List));
            }
            catch (Exception ex)
            {
                ViewData["Alert"] = "An error occurred: " + ex.Message;
                var vm = new EquipmentViewModel(_IWarehouseService.GetEquipment(id), User.FindFirstValue(ClaimTypes.NameIdentifier));
                return View(vm);
            }


        }

        [HttpGet]

        public IActionResult DeleteEquipment(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = _IWarehouseService.GetEquipment(id);


            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        [HttpPost, ActionName("DeleteEquipment")]
        public IActionResult DeleteEquipmentConfirmed(int id)
        {
            _IWarehouseService.DeleteEquipment(id);
            TempData["Alert"] = "You have deleted equipment succesfully";

            return RedirectToAction("List");
        }
    }
}

RentalService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentalService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/js/index.global.js"></script>

    <link rel="stylesheet" href="~/RentalService.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportRentalWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="List">Warehouse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="ViewCalendar">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rental" asp-action="ViewRentals">Rentals</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Wyloguj</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SportRentalWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.global.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>